### ISSUE TITLE
[1pt] Tracking Properties de Votaciones

### ISSUE THREAD

**Issue by jmperezra** [IESAM-DAM/avila-en-tapas#172]
## Issue
Se pide trackear eventos del usuario para conocer su comportamiento. En esta ocasión, los builds para tracker están ya hechos. Se pide:
- [x] Lanzar un evento cuando el usuario pulsa en un item de tapa-review (ver el build relacionado en EventProperties).
- [x] Lanzar un evento cuando el usuario vota una tapa. El evento se mide al pulsar el botón votar.
- [x] Lanzar un evento cuando el usuario se arrepiente de votar y pulsa el botón cancelar.

Nota: los modelos que hay que enviar están hechos, el caso de uso tb, es el mismo en todos los eventos.
